a=$((RANDOM%90+10));
b=$((RANDOM%90+10));
c=$((RANDOM%90+10));
d=$((RANDOM%90+10));
e=$((RANDOM%90+10));
echo " 5 Random 2 digit numbers are : $a $b $c $d $e";
sum=$(($a +$b +$c +$d +$e));
average=$(($sum/5));
echo "Sum:" $sum;
echo "Average:" $average;
